<script setup>
defineProps({
  confirmingEntry: { type: Object, default: null }, tagModalOpen: { type: Boolean, required: true }, tagInput: { type: String, required: true }, tags: { type: Array, required: true }, editingTagId: { type: String, default: null }, editingTagName: { type: String, required: true }, detailTitle: { type: String, required: true }, paginatedDetailRows: { type: Array, required: true }, detailRows: { type: Array, required: true }, detailPage: { type: Number, required: true }, detailTotalPages: { type: Number, required: true }, detailVisibleRange: { type: String, required: true }, pageSize: { type: Number, required: true }, selectedEntryDetail: { type: Object, default: null }, balancesHidden: { type: Boolean, required: true }, error: { type: String, required: true }, formatAmount: { type: Function, required: true }, formatTime: { type: Function, required: true }, accountLabel: { type: Function, required: true }
})
defineEmits(['cancel-remove', 'confirm-remove', 'close-tag-modal', 'submit-tag', 'update:tag-input', 'start-tag-edit', 'save-tag', 'cancel-tag-edit', 'update:editing-tag-name', 'remove-tag', 'close-details', 'open-entry-detail', 'update:detail-page', 'close-entry-detail'])
</script>

<template>
  <div v-if="confirmingEntry" class="dialog-backdrop" @click.self="$emit('cancel-remove')"><section class="confirm-dialog" role="alertdialog" aria-modal="true"><h2>Xoá giao dịch?</h2><p>{{ confirmingEntry.note || 'Giao dịch không có ghi chú' }} · {{ confirmingEntry.amount < 0 ? '' : '+' }}{{ formatAmount(confirmingEntry.amount) }}. Thao tác này không thể hoàn tác.</p><div class="dialog-actions"><button type="button" class="cancel-delete-btn" @click="$emit('cancel-remove')">Huỷ</button><button type="button" class="confirm-delete-btn" @click="$emit('confirm-remove')">Xoá</button></div></section></div>
  <div v-if="tagModalOpen" class="dialog-backdrop" @click.self="$emit('close-tag-modal')"><section class="confirm-dialog tag-dialog" role="dialog" aria-modal="true"><div class="debt-details-heading"><h2>Quản lý thẻ</h2><button type="button" class="close-details-btn" aria-label="Đóng" @click="$emit('close-tag-modal')">×</button></div><form class="tag-add-form" @submit.prevent="$emit('submit-tag')"><input :value="tagInput" class="note-input" type="text" placeholder="Tên thẻ mới" @input="$emit('update:tag-input', $event.target.value)" /><button type="submit" class="save-balance-btn">Thêm</button></form><p v-if="error" class="debt-modal-error">{{ error }}</p><div class="tag-list"><div v-for="tag in tags" :key="tag.id" class="tag-list-row"><template v-if="editingTagId === tag.id"><input :value="editingTagName" class="note-input" type="text" @input="$emit('update:editing-tag-name', $event.target.value)" @keyup.enter="$emit('save-tag', tag)" /><button type="button" class="tag-action-btn" @click="$emit('save-tag', tag)">Lưu</button><button type="button" class="tag-action-btn" @click="$emit('cancel-tag-edit')">Huỷ</button></template><template v-else><span>{{ tag.name }}</span><button type="button" class="tag-action-btn" @click="$emit('start-tag-edit', tag)">Sửa</button><button type="button" class="tag-action-btn tag-delete-btn" @click="$emit('remove-tag', tag)">Xoá</button></template></div></div></section></div>
  <div v-if="detailTitle" class="dialog-backdrop" @click.self="$emit('close-details')"><section class="confirm-dialog detail-dialog" role="dialog" aria-modal="true"><div class="debt-details-heading"><h2>{{ detailTitle }}</h2><button type="button" class="close-details-btn" aria-label="Đóng" @click="$emit('close-details')">×</button></div><div class="detail-list"><button v-for="row in paginatedDetailRows" :key="row.id" type="button" class="row" @click="$emit('open-entry-detail', row)"><span class="row-note">{{ row.note || '—' }} <span class="row-meta"><span class="account-badge">{{ accountLabel(row.account_type) }}</span><span v-if="row.tag" class="tag-badge">{{ row.tag }}</span><span v-if="row.counts_toward_daily === false" class="daily-excluded-badge">Không tính ngày</span></span></span><span class="row-time">{{ formatTime(row.created_at) }}</span><span class="row-amount" :class="row.amount < 0 ? 'neg' : 'pos'">{{ row.amount < 0 ? '' : '+' }}{{ formatAmount(row.amount) }}</span><span class="row-balance" :class="{ masked: balancesHidden }">{{ balancesHidden ? '••••••' : formatAmount(row.accountBalance) }}</span></button></div><nav v-if="detailRows.length > pageSize" class="pagination"><span>{{ detailVisibleRange }}</span><div class="pagination-controls"><button type="button" :disabled="detailPage === 1" @click="$emit('update:detail-page', detailPage - 1)">Trước</button><span>{{ detailPage }} / {{ detailTotalPages }}</span><button type="button" :disabled="detailPage === detailTotalPages" @click="$emit('update:detail-page', detailPage + 1)">Sau</button></div></nav></section></div>
  <div v-if="selectedEntryDetail" class="dialog-backdrop" @click.self="$emit('close-entry-detail')"><section class="confirm-dialog entry-detail-dialog" role="dialog" aria-modal="true"><div class="debt-details-heading"><h2>Chi tiết giao dịch</h2><button type="button" class="close-details-btn" aria-label="Đóng" @click="$emit('close-entry-detail')">×</button></div><p class="entry-detail-amount" :class="selectedEntryDetail.amount < 0 ? 'neg' : 'pos'">{{ selectedEntryDetail.amount < 0 ? '' : '+' }}{{ formatAmount(selectedEntryDetail.amount) }} ₫</p><p class="entry-detail-note">{{ selectedEntryDetail.note || 'Không có ghi chú' }}</p></section></div>
</template>
