<script setup>
import { computed, ref, watch } from 'vue'

const props = defineProps({ open: Boolean, debts: Array, balancesHidden: Boolean, formatAmount: Function, error: String })
const emit = defineEmits(['close', 'create', 'increase', 'pay', 'edit', 'delete', 'save-plan', 'delete-plan'])
const mode = ref('list')
const selectedId = ref(null)
const name = ref('')
const amount = ref('')
const note = ref('')
const planMonth = ref(currentMonth())
const planAmount = ref('')
const paymentAccount = ref('bank')
const plans = ref([])
const editingPlanMonth = ref(null)
const confirmation = ref(null)
const selectedDebt = computed(() => props.debts.find((debt) => debt.id === selectedId.value) || null)

watch(() => props.open, (open) => { if (open) resetForm() })

function currentMonth() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}` }
function monthLabel(month) { return `${month.slice(5, 7)}/${month.slice(0, 4)}` }
function parseAmount(value) { const parsed = Math.abs(Number(String(value).trim().replace(/[, ]/g, ''))); return Number.isFinite(parsed) && parsed > 0 ? parsed : null }
function resetForm() { mode.value = 'list'; selectedId.value = null; name.value = ''; amount.value = ''; note.value = ''; planMonth.value = currentMonth(); planAmount.value = ''; paymentAccount.value = 'bank'; plans.value = []; editingPlanMonth.value = null; confirmation.value = null }
function openDebt(debt) { selectedId.value = debt.id; mode.value = 'detail' }
function startCreate() { name.value = ''; amount.value = ''; note.value = ''; plans.value = []; mode.value = 'create' }
function startEdit() { name.value = selectedDebt.value.name; note.value = selectedDebt.value.note || ''; mode.value = 'edit' }
function startIncrease() { amount.value = ''; note.value = ''; plans.value = []; mode.value = 'increase' }
function startPayment() { amount.value = ''; note.value = ''; paymentAccount.value = 'bank'; mode.value = 'pay' }
function startPlanEdit(plan = null) { editingPlanMonth.value = plan?.month || null; planMonth.value = plan ? plan.month.slice(0, 7) : currentMonth(); planAmount.value = plan ? String(plan.amount) : ''; mode.value = 'plan' }
function addDraftPlan() { const value = parseAmount(planAmount.value); const month = `${planMonth.value}-01`; if (!value || !planMonth.value) return; const existing = plans.value.find((plan) => plan.month === month); if (existing) existing.amount += value; else plans.value.push({ month, amount: value }); plans.value.sort((a, b) => a.month.localeCompare(b.month)); planAmount.value = '' }
function requestConfirmation(action, title, message, payload) { confirmation.value = { action, title, message, payload } }
function submitCreate() { const openingAmount = parseAmount(amount.value); if (!name.value.trim() || !openingAmount) return; requestConfirmation('create', 'Tạo khoản nợ?', `Tạo “${name.value.trim()}” với dư nợ ban đầu ${props.formatAmount(openingAmount)} ₫.`, { name: name.value.trim(), note: note.value.trim() || null, amount: openingAmount, plans: [...plans.value] }) }
function submitEdit() { if (!selectedDebt.value || !name.value.trim()) return; requestConfirmation('edit', 'Cập nhật khoản nợ?', `Lưu thông tin mới cho “${name.value.trim()}”.`, { debtId: selectedDebt.value.id, name: name.value.trim(), note: note.value.trim() || null }) }
function submitIncrease() { const value = parseAmount(amount.value); if (!selectedDebt.value || !value) return; requestConfirmation('increase', 'Ghi phát sinh nợ?', `Cộng ${props.formatAmount(value)} ₫ vào tổng nợ “${selectedDebt.value.name}”.`, { debtId: selectedDebt.value.id, amount: value, note: note.value.trim() || null, plans: [...plans.value] }) }
function submitPayment() { const value = parseAmount(amount.value); if (!selectedDebt.value || !value || value > selectedDebt.value.balance) return; const labels = { bank: 'Tài khoản', wallet: 'Ví', cash: 'Tiền mặt' }; requestConfirmation('pay', 'Xác nhận trả nợ?', `Trừ ${props.formatAmount(value)} ₫ khỏi ${labels[paymentAccount.value]} và tổng nợ “${selectedDebt.value.name}”.`, { debtId: selectedDebt.value.id, amount: value, accountType: paymentAccount.value, note: note.value.trim() || null }) }
function submitPlan() { const value = parseAmount(planAmount.value); if (!selectedDebt.value || !planMonth.value || !value) return; const verb = editingPlanMonth.value ? 'Cập nhật' : 'Thêm'; requestConfirmation('save-plan', `${verb} lịch trả?`, `${verb} kế hoạch trả ${props.formatAmount(value)} ₫ cho tháng ${monthLabel(planMonth.value)}.`, { debtId: selectedDebt.value.id, month: `${planMonth.value}-01`, amount: value }) }
function requestPlanDelete(plan) { requestConfirmation('delete-plan', 'Xoá lịch trả?', `Xoá kế hoạch trả ${props.formatAmount(plan.amount)} ₫ của tháng ${monthLabel(plan.month)}.`, { debtId: selectedDebt.value.id, month: plan.month }) }
function requestDebtDelete() { requestConfirmation('delete', 'Xoá khoản nợ?', `Xoá “${selectedDebt.value.name}” cùng toàn bộ lịch trả và lịch sử nợ. Thao tác này không thể hoàn tác.`, { debtId: selectedDebt.value.id }) }
function confirmAction() { const action = confirmation.value; if (!action) return; emit(action.action, action.payload); mode.value = action.action === 'create' || action.action === 'delete' ? 'list' : 'detail'; confirmation.value = null }
</script>

<template>
  <div v-if="open" class="dialog-backdrop debt-manager-backdrop" @click.self="$emit('close')">
    <section class="confirm-dialog debt-manager" role="dialog" aria-modal="true" aria-labelledby="debt-manager-title">
      <div class="debt-details-heading"><div><p class="settings-kicker">Theo dõi nghĩa vụ</p><h2 id="debt-manager-title">{{ mode === 'list' ? 'Các khoản nợ' : mode === 'create' ? 'Thêm khoản nợ' : mode === 'plan' ? 'Lịch trả nợ' : selectedDebt?.name }}</h2></div><button type="button" class="close-details-btn" aria-label="Đóng" @click="$emit('close')">×</button></div>
      <template v-if="mode === 'list'"><p>Chọn một khoản để xem lịch trả, phát sinh thêm hoặc thanh toán.</p><div v-if="debts.length" class="debt-account-list"><button v-for="debt in debts" :key="debt.id" type="button" class="debt-account-row" @click="openDebt(debt)"><span><strong>{{ debt.name }}</strong><small>Tháng này còn {{ formatAmount(debt.monthRemaining) }} ₫</small></span><strong :class="{ masked: balancesHidden }">{{ balancesHidden ? '••••••' : formatAmount(debt.balance) }} ₫</strong></button></div><p v-else class="empty debt-empty">Chưa có khoản nợ nào.</p><button type="button" class="debt-add-btn debt-primary-btn" @click="startCreate">+ Thêm khoản nợ</button></template>
      <form v-else-if="mode === 'create' || mode === 'increase'" class="debt-modal-form" @submit.prevent="mode === 'create' ? submitCreate() : submitIncrease()"><label v-if="mode === 'create'" class="debt-field-label">Tên khoản nợ<input v-model="name" class="note-input" type="text" placeholder="Ví dụ: Thẻ tín dụng" autofocus></label><label class="debt-field-label">{{ mode === 'create' ? 'Dư nợ ban đầu' : 'Phát sinh thêm' }}<input v-model="amount" class="amount-input" type="text" inputmode="numeric" placeholder="Số tiền"></label><label class="debt-field-label">Ghi chú<input v-model="note" class="note-input" type="text" placeholder="Tuỳ chọn"></label><div class="debt-plan-box"><strong>Phân bổ lịch trả <small>(tuỳ chọn)</small></strong><div class="debt-plan-add"><input v-model="planMonth" type="month"><input v-model="planAmount" class="amount-input" type="text" inputmode="numeric" placeholder="Số tiền"><button type="button" @click="addDraftPlan">Thêm</button></div><div v-if="plans.length" class="debt-plan-list"><span v-for="plan in plans" :key="plan.month">{{ monthLabel(plan.month) }} · {{ formatAmount(plan.amount) }} ₫ <button type="button" aria-label="Xoá kế hoạch" @click="plans = plans.filter((item) => item !== plan)">×</button></span></div></div><p v-if="error" class="debt-modal-error">{{ error }}</p><div class="dialog-actions"><button type="button" class="cancel-delete-btn" @click="mode = mode === 'create' ? 'list' : 'detail'">Huỷ</button><button type="submit" class="confirm-delete-btn">Tiếp tục</button></div></form>
      <form v-else-if="mode === 'edit' && selectedDebt" class="debt-modal-form" @submit.prevent="submitEdit"><label class="debt-field-label">Tên khoản nợ<input v-model="name" class="note-input" type="text" autofocus></label><label class="debt-field-label">Ghi chú<input v-model="note" class="note-input" type="text" placeholder="Tuỳ chọn"></label><p v-if="error" class="debt-modal-error">{{ error }}</p><div class="dialog-actions"><button type="button" class="cancel-delete-btn" @click="mode = 'detail'">Huỷ</button><button type="submit" class="confirm-delete-btn">Tiếp tục</button></div></form>
      <template v-else-if="mode === 'detail' && selectedDebt"><div class="debt-detail-total"><span>Tổng nợ còn lại</span><strong :class="{ masked: balancesHidden }">{{ balancesHidden ? '••••••' : formatAmount(selectedDebt.balance) }} ₫</strong></div><div class="debt-month-status"><span>Kế hoạch tháng này <strong>{{ formatAmount(selectedDebt.monthPlanned) }} ₫</strong></span><span>Đã trả <strong>{{ formatAmount(selectedDebt.monthPaid) }} ₫</strong></span><span>Còn trả <strong>{{ formatAmount(selectedDebt.monthRemaining) }} ₫</strong></span></div><div class="debt-detail-actions"><button type="button" @click="startIncrease">+ Phát sinh</button><button type="button" @click="startPayment">Thanh toán</button></div><div class="debt-management-actions"><button type="button" @click="startEdit">Sửa khoản nợ</button><button type="button" class="debt-delete-btn" @click="requestDebtDelete">Xoá khoản nợ</button></div><div class="debt-section-heading"><h3>Lịch trả</h3><button type="button" @click="startPlanEdit">+ Thêm lịch</button></div><div class="debt-plan-history"><p v-if="!selectedDebt.plans.length">Chưa có kế hoạch trả.</p><div v-for="plan in selectedDebt.plans" :key="plan.month"><span>{{ monthLabel(plan.month) }}</span><span>{{ formatAmount(plan.amount) }} ₫</span><span class="debt-row-actions"><button type="button" @click="startPlanEdit(plan)">Sửa</button><button type="button" @click="requestPlanDelete(plan)">Xoá</button></span></div></div><h3>Phát sinh gần đây</h3><div class="debt-entry-history"><div v-for="entry in selectedDebt.entries.slice(0, 6)" :key="entry.id"><span>{{ entry.note || (entry.amount < 0 ? 'Thanh toán' : 'Phát sinh') }}</span><strong :class="entry.amount < 0 ? 'pos' : 'neg'">{{ entry.amount < 0 ? '−' : '+' }}{{ formatAmount(Math.abs(entry.amount)) }} ₫</strong></div></div><button type="button" class="debt-back-btn" @click="mode = 'list'">← Danh sách khoản nợ</button></template>
      <form v-else-if="mode === 'plan' && selectedDebt" class="debt-modal-form" @submit.prevent="submitPlan"><label class="debt-field-label">Tháng trả nợ<input v-model="planMonth" type="month" class="note-input"></label><label class="debt-field-label">Số tiền dự kiến trả<input v-model="planAmount" class="amount-input" type="text" inputmode="numeric" autofocus></label><p v-if="error" class="debt-modal-error">{{ error }}</p><div class="dialog-actions"><button type="button" class="cancel-delete-btn" @click="mode = 'detail'">Huỷ</button><button type="submit" class="confirm-delete-btn">Tiếp tục</button></div></form>
      <form v-else-if="mode === 'pay' && selectedDebt" class="debt-modal-form" @submit.prevent="submitPayment"><p>Thanh toán cho <strong>{{ selectedDebt.name }}</strong>. Số tiền sẽ trừ khỏi số dư và tổng nợ cùng lúc.</p><label class="debt-field-label">Số tiền trả (tối đa {{ formatAmount(selectedDebt.balance) }} ₫)<input v-model="amount" class="amount-input" type="text" inputmode="numeric" autofocus></label><label class="debt-field-label">Trừ từ nguồn tiền<select v-model="paymentAccount" class="note-input"><option value="bank">Tài khoản</option><option value="wallet">Ví</option><option value="cash">Tiền mặt</option></select></label><label class="debt-field-label">Ghi chú<input v-model="note" class="note-input" type="text" placeholder="Tuỳ chọn"></label><p v-if="error" class="debt-modal-error">{{ error }}</p><div class="dialog-actions"><button type="button" class="cancel-delete-btn" @click="mode = 'detail'">Huỷ</button><button type="submit" class="confirm-delete-btn">Tiếp tục</button></div></form>
      <div v-if="confirmation" class="debt-confirm-overlay" role="alertdialog" aria-modal="true"><section class="debt-confirm-card"><h3>{{ confirmation.title }}</h3><p>{{ confirmation.message }}</p><div class="dialog-actions"><button type="button" class="cancel-delete-btn" @click="confirmation = null">Quay lại sửa</button><button type="button" class="confirm-delete-btn" @click="confirmAction">Xác nhận</button></div></section></div>
    </section>
  </div>
</template>
