<script setup>
defineProps({
  entries: { type: Array, required: true }, historyPeriod: { type: String, required: true }, searchQuery: { type: String, required: true }, dateSearchMode: { type: String, required: true }, dateFrom: { type: String, required: true }, dateTo: { type: String, required: true }, historyRows: { type: Array, required: true }, dailySummaries: { type: Array, required: true }, paginatedDailySummaries: { type: Array, required: true }, chartBuckets: { type: Array, required: true }, chartMax: { type: Number, required: true }, chartIncomeTotal: { type: Number, required: true }, chartExpenseTotal: { type: Number, required: true }, currentPage: { type: Number, required: true }, dailySummaryPages: { type: Number, required: true }, dailySummaryRange: { type: String, required: true }, pageSize: { type: Number, required: true }, formatAmount: { type: Function, required: true }
})
defineEmits(['update:history-period', 'update:search-query', 'update:date-search-mode', 'update:date-from', 'update:date-to', 'update:current-page', 'reset-date-search', 'open-details'])
</script>

<template>
  <section class="history-page">
    <div v-if="!entries.length" class="empty">Sổ còn trống. Ghi khoản chi tiêu đầu tiên phía trên.</div>
    <template v-else>
      <div class="history-filters" aria-label="Lọc lịch sử giao dịch"><button v-for="period in [['day', 'Ngày'], ['week', 'Tuần'], ['month', 'Tháng']]" :key="period[0]" type="button" :class="{ active: historyPeriod === period[0] }" @click="$emit('update:history-period', period[0])">{{ period[1] }}</button></div>
      <div class="history-search-tools"><label class="search-field" for="transaction-search"><span>Tên hoặc số tiền</span><input id="transaction-search" :value="searchQuery" type="search" placeholder="Ví dụ: ăn trưa hoặc 50.000" @input="$emit('update:search-query', $event.target.value)" /></label><div class="date-search"><div class="date-mode-tabs"><button type="button" :class="{ active: dateSearchMode === 'day' }" @click="$emit('update:date-search-mode', 'day'); $emit('update:date-to', '')">Theo ngày</button><button type="button" :class="{ active: dateSearchMode === 'range' }" @click="$emit('update:date-search-mode', 'range')">Khoảng ngày</button></div><div class="date-inputs"><label>{{ dateSearchMode === 'day' ? 'Ngày' : 'Từ ngày' }} <input :value="dateFrom" type="date" @input="$emit('update:date-from', $event.target.value)" /></label><label v-if="dateSearchMode === 'range'">Đến ngày <input :value="dateTo" type="date" @input="$emit('update:date-to', $event.target.value)" /></label><button v-if="dateFrom || dateTo" type="button" class="clear-date-btn" @click="$emit('reset-date-search')">Xoá lọc ngày</button></div></div></div>
      <div v-if="!historyRows.length" class="empty">Không tìm thấy giao dịch phù hợp.</div>
      <template v-else><div v-if="historyPeriod === 'day'" class="summary-list"><button v-for="summary in paginatedDailySummaries" :key="summary.key" type="button" class="day-summary-row" @click="$emit('open-details', summary.rows, summary.label)"><span class="day-summary-label">{{ summary.label }}</span><span class="day-summary-values"><small class="pos">+{{ formatAmount(summary.income) }}</small><small class="neg">−{{ formatAmount(summary.expense) }}</small></span><strong :class="summary.net < 0 ? 'neg' : 'pos'">{{ summary.net < 0 ? '' : '+' }}{{ formatAmount(summary.net) }}</strong></button></div><div v-else class="chart-card"><div class="bar-chart" :class="{ compact: historyPeriod === 'month' }"><button v-for="bucket in chartBuckets" :key="bucket.key" type="button" class="bar-column" :disabled="!bucket.rows.length" @click="$emit('open-details', bucket.rows, historyPeriod === 'week' ? bucket.label : `Ngày ${bucket.label} trong tháng`)"><span class="bar-stack"><span class="bar income-bar" :style="{ height: `${bucket.income / chartMax * 100}%` }"></span><span class="bar expense-bar" :style="{ height: `${bucket.expense / chartMax * 100}%` }"></span></span><span class="bar-label">{{ bucket.label }}</span></button></div><p class="chart-summary">Tổng chi: <strong class="neg">−{{ formatAmount(chartExpenseTotal) }}</strong> · Tổng thu: <strong class="pos">+{{ formatAmount(chartIncomeTotal) }}</strong></p></div><div v-if="historyPeriod === 'day' && dailySummaries.length > pageSize" class="summary-pagination pagination"><span>{{ dailySummaryRange }}</span><div class="pagination-controls"><button type="button" :disabled="currentPage === 1" @click="$emit('update:current-page', currentPage - 1)">Trước</button><span>Trang {{ currentPage }} / {{ dailySummaryPages }}</span><button type="button" :disabled="currentPage === dailySummaryPages" @click="$emit('update:current-page', currentPage + 1)">Sau</button></div></div></template>
    </template>
  </section>
</template>
